graph [
   comment "Generated by ViSiDiA" 
   directed 0
   node [
      id 0
      label "N"
      graphics [
         x 666
         y 307
      ]
   ]
   node [
      id 1
      label "N"
      graphics [
         x 575
         y 386
      ]
   ]
   node [
      id 2
      label "N"
      graphics [
         x 666
         y 436
      ]
   ]
   node [
      id 3
      label "N"
      graphics [
         x 765
         y 384
      ]
   ]
   node [
      id 4
      label "N"
      graphics [
         x 666
         y 541
      ]
   ]
   node [
      id 5
      label "N"
      graphics [
         x 666
         y 632
      ]
   ]
   node [
      id 6
      label "N"
      graphics [
         x 478
         y 307
      ]
   ]
   node [
      id 7
      label "N"
      graphics [
         x 852
         y 307
      ]
   ]
   edge [
      source 0
      target 1
      label ""
      weight 1.0
   ]
   edge [
      source 0
      target 2
      label ""
      weight 1.0
   ]
   edge [
      source 0
      target 3
      label ""
      weight 1.0
   ]
   edge [
      source 2
      target 4
      label ""
      weight 1.0
   ]
   edge [
      source 4
      target 5
      label ""
      weight 1.0
   ]
   edge [
      source 0
      target 6
      label ""
      weight 1.0
   ]
   edge [
      source 0
      target 7
      label ""
      weight 1.0
   ]
]