graph [
   comment "Generated by ViSiDiA" 
   directed 0
   node [
      id 0
      label "N"
      graphics [
         x 545
         y 297
      ]
   ]
   node [
      id 1
      label "N"
      graphics [
         x 667
         y 297
      ]
   ]
   node [
      id 2
      label "N"
      graphics [
         x 791
         y 297
      ]
   ]
   node [
      id 3
      label "N"
      graphics [
         x 791
         y 394
      ]
   ]
   node [
      id 4
      label "W"
      graphics [
         x 791
         y 489
      ]
   ]
   node [
      id 5
      label "N"
      graphics [
         x 670
         y 394
      ]
   ]
   node [
      id 6
      label "N"
      graphics [
         x 672
         y 489
      ]
   ]
   node [
      id 7
      label "N"
      graphics [
         x 547
         y 393
      ]
   ]
   node [
      id 8
      label "N"
      graphics [
         x 546
         y 489
      ]
   ]
   node [
      id 9
      label "N"
      graphics [
         x 906
         y 297
      ]
   ]
   node [
      id 10
      label "N"
      graphics [
         x 909
         y 394
      ]
   ]
   node [
      id 11
      label "N"
      graphics [
         x 910
         y 489
      ]
   ]
   edge [
      source 0
      target 1
      label ""
      weight 1.0
   ]
   edge [
      source 1
      target 2
      label ""
      weight 1.0
   ]
   edge [
      source 2
      target 3
      label ""
      weight 1.0
   ]
   edge [
      source 3
      target 4
      label ""
      weight 1.0
   ]
   edge [
      source 3
      target 5
      label ""
      weight 1.0
   ]
   edge [
      source 4
      target 6
      label ""
      weight 1.0
   ]
   edge [
      source 5
      target 7
      label ""
      weight 1.0
   ]
   edge [
      source 6
      target 8
      label ""
      weight 1.0
   ]
   edge [
      source 0
      target 7
      label ""
      weight 1.0
   ]
   edge [
      source 7
      target 8
      label ""
      weight 1.0
   ]
   edge [
      source 1
      target 5
      label ""
      weight 1.0
   ]
   edge [
      source 5
      target 6
      label ""
      weight 1.0
   ]
   edge [
      source 2
      target 9
      label ""
      weight 1.0
   ]
   edge [
      source 3
      target 10
      label ""
      weight 1.0
   ]
   edge [
      source 4
      target 11
      label ""
      weight 1.0
   ]
   edge [
      source 11
      target 10
      label ""
      weight 1.0
   ]
   edge [
      source 10
      target 9
      label ""
      weight 1.0
   ]
]